### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mrmartineau** [mrmartineau/cloze-test#1]
From the few requests I've had recently, here's a list of all the new features I will be implementing soon:
- [ ] Improve code & interface
  - [x] Use Ractive
  - [ ] Remove jQuery dependency
- [ ] Better styling for printouts ([#2](https://github.com/mrmartineau/martineau.tv/issues/5))
- [x] Turn the blanks into underscores _ with automatic numbering ([#5](https://github.com/mrmartineau/martineau.tv/issues/5))
- [x] Move Cloze code to new Github repo
- [x] Move cloze to  new domain - zander.io/cloze-test/
